[package]
name = "cindy-next-rust"
version = "0.1.0"
authors = ["heyrict <xiezh0831@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
async-graphql = "1.16"
async-graphql-actix-web = "1.4.17"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-web-actors = "2.0.0"
anyhow = "^1.0"

tokio = { version = "0.2", features = ["time", "stream"] }
chrono = "0.4"
futures = "0.3.0"
diesel = { version = "^1.4", features = ["postgres", "r2d2", "chrono"] }
