[package]
name = "cindy-next-rust"
version = "0.1.0"
authors = ["heyrict <xiezh0831@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
log = "^0.4"
env_logger = "^0.7"

async-graphql = "^2.4"
async-graphql-actix-web = "^2.4"
actix-web = "3.0"
actix-rt = "~1.1"
actix-web-actors = "3.0.0"
anyhow = "^1.0"

ring = "^0.16"
rand = "^0.7"
base64 = "^0.12"
frank_jwt = "^3.1"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
#bitflags = "^1.2"

time = "^0.2"
tokio = { version = "0.2", features = ["time", "stream", "sync"] }
chrono = "0.4"
futures = "0.3.0"
diesel = { version = "^1.4", features = ["postgres", "r2d2", "chrono"] }
#diesel = { git = "https://github.com/diesel-rs/diesel", branch = "master", features = ["postgres", "r2d2", "chrono"] }
lazy_static = "^1.4"
