-- This file was automatically created by Diesel to setup helper functions
-- and other internal bookkeeping. This file is safe to edit, any future
-- changes will be added to existing projects as new migrations.

DROP FUNCTION IF EXISTS diesel_manage_updated_at(_tbl regclass);
DROP FUNCTION IF EXISTS diesel_set_updated_at();

--------------------------------------------
--                                        --
-- The following are generated by pg_dump --
--                                        --
--------------------------------------------

-- Drop triggers

DROP TRIGGER IF EXISTS update_puzzle_modified_trigger ON public.puzzle CASCADE;
DROP TRIGGER IF EXISTS update_hint_modified_trigger ON public.hint;
DROP TRIGGER IF EXISTS update_chatmessage_modified_trigger ON public.chatmessage;
DROP TRIGGER IF EXISTS update_answer_dialogue_answer_trigger ON public.dialogue;
DROP TRIGGER IF EXISTS maybe_delete_tag_after_puzzle_tag_delete_trigger ON public.puzzle_tag;
DROP TRIGGER IF EXISTS add_puzzle_chatroom_after_puzzle_insert_trigger ON public.puzzle;
DROP TRIGGER IF EXISTS add_dialogue_qno_before_dialogue_insert_trigger ON public.dialogue;

-- Drop functions

DROP FUNCTION IF EXISTS public.add_dialogue_qno_before_dialogue_insert();
DROP FUNCTION IF EXISTS public.add_puzzle_chatroom_after_puzzle_insert();
DROP FUNCTION IF EXISTS public.dialogue_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone);
DROP FUNCTION IF EXISTS public.direct_message_group(user_id integer);
DROP FUNCTION IF EXISTS public.maybe_delete_tag_after_puzzle_tag_delete();
DROP FUNCTION IF EXISTS public.puzzle_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone);
DROP FUNCTION IF EXISTS public.star_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone);
DROP FUNCTION IF EXISTS public.star_sum_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone);
DROP FUNCTION IF EXISTS public.update_chatmessage_modified();
DROP FUNCTION IF EXISTS public.update_dialogue_answer();
DROP FUNCTION IF EXISTS public.update_hint_modified();
DROP FUNCTION IF EXISTS public.update_puzzle_modified();
DROP FUNCTION IF EXISTS public.user_puzzle_genre_groups("userId" integer);
DROP FUNCTION IF EXISTS public.user_star_groups("userId" integer);

-- Drop tables

DROP TABLE IF EXISTS public.hasura_user_ranking_trigger CASCADE;
DROP TABLE IF EXISTS public.hasura_direct_message_group_trigger CASCADE;
DROP TABLE IF EXISTS public.hasura_int_groupby_trigger CASCADE;
DROP TABLE IF EXISTS public.auth_group CASCADE;
DROP TABLE IF EXISTS public.auth_group_permissions CASCADE;
DROP TABLE IF EXISTS public.auth_permission CASCADE;
DROP TABLE IF EXISTS public.award CASCADE;
DROP TABLE IF EXISTS public.award_application CASCADE;
DROP TABLE IF EXISTS public.bookmark CASCADE;
DROP TABLE IF EXISTS public.chatmessage CASCADE;
DROP TABLE IF EXISTS public.chatroom CASCADE;
DROP TABLE IF EXISTS public.comment CASCADE;
DROP TABLE IF EXISTS public.dialogue CASCADE;
DROP TABLE IF EXISTS public.direct_message CASCADE;
DROP TABLE IF EXISTS public.django_admin_log CASCADE;
DROP TABLE IF EXISTS public.django_content_type CASCADE;
DROP TABLE IF EXISTS public.django_migrations CASCADE;
DROP TABLE IF EXISTS public.django_session CASCADE;
DROP TABLE IF EXISTS public.event CASCADE;
DROP TABLE IF EXISTS public.event_award CASCADE;
DROP TABLE IF EXISTS public.favorite_chatroom CASCADE;
DROP TABLE IF EXISTS public.hint CASCADE;
DROP TABLE IF EXISTS public.puzzle CASCADE;
DROP TABLE IF EXISTS public.puzzle_tag CASCADE;
DROP TABLE IF EXISTS public.replay CASCADE;
DROP TABLE IF EXISTS public.replay_dialogue CASCADE;
DROP TABLE IF EXISTS public.schedule CASCADE;
DROP TABLE IF EXISTS public.star CASCADE;
DROP TABLE IF EXISTS public.sui_hei_puzzle_tokenize_cache CASCADE;
DROP TABLE IF EXISTS public.tag CASCADE;
DROP TABLE IF EXISTS public.sui_hei_user_groups CASCADE;
DROP TABLE IF EXISTS public."user" CASCADE;
DROP TABLE IF EXISTS public.sui_hei_user_user_permissions CASCADE;
DROP TABLE IF EXISTS public.user_award CASCADE;
