-- This file was automatically created by Diesel to setup helper functions
-- and other internal bookkeeping. This file is safe to edit, any future
-- changes will be added to existing projects as new migrations.



-- Sets up a trigger for the given table to automatically set a column called
-- `updated_at` whenever the row is modified (unless `updated_at` was included
-- in the modified columns)
--
-- # Example
--
-- ```sql
-- CREATE TABLE users (id SERIAL PRIMARY KEY, updated_at TIMESTAMP NOT NULL DEFAULT NOW());
--
-- SELECT diesel_manage_updated_at('users');
-- ```
CREATE OR REPLACE FUNCTION diesel_manage_updated_at(_tbl regclass) RETURNS VOID AS $$
BEGIN
    EXECUTE format('CREATE TRIGGER set_updated_at BEFORE UPDATE ON %s
                    FOR EACH ROW EXECUTE PROCEDURE diesel_set_updated_at()', _tbl);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION diesel_set_updated_at() RETURNS trigger AS $$
BEGIN
    IF (
        NEW IS DISTINCT FROM OLD AND
        NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at
    ) THEN
        NEW.updated_at := current_timestamp;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


--------------------------------------------
--                                        --
-- The following are generated by pg_dump --
--                                        --
--------------------------------------------

--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4
-- Dumped by pg_dump version 12.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', 'public', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--------------------------------
-- Dropped pgcrypto extension --
--------------------------------
----
---- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
----
--
--CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
--
--
----
---- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
----
--
--COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';
--
--------------------------------


--
-- Name: add_dialogue_qno_before_dialogue_insert(); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.add_dialogue_qno_before_dialogue_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
  qno integer;
begin
  select count(id) + 1 as qno from dialogue where puzzle_id = NEW.puzzle_id into qno;
  NEW.qno = qno;
  return NEW;
end;
$$;


ALTER FUNCTION public.add_dialogue_qno_before_dialogue_insert() OWNER TO cindy;

--
-- Name: add_puzzle_chatroom_after_puzzle_insert(); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.add_puzzle_chatroom_after_puzzle_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
declare
  existing_chatroom_id integer;
begin
  select id from chatroom where name = format('puzzle-%s', NEW.id) into existing_chatroom_id;
  if existing_chatroom_id IS NOT NULL then
    delete from chatmessages where chatroom_id = existing_chatroom_id;
    update chatroom set description = '', user_id = NEW.user_id;
  else
    insert into chatroom (name, description, user_id) values (format('puzzle-%s', NEW.id), '', NEW.user_id);
  end if;
  return NEW;
end;
$$;


ALTER FUNCTION public.add_puzzle_chatroom_after_puzzle_insert() OWNER TO cindy;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: hasura_user_ranking_trigger; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.hasura_user_ranking_trigger (
    user_id integer NOT NULL,
    value bigint NOT NULL
);


ALTER TABLE public.hasura_user_ranking_trigger OWNER TO cindy;

--
-- Name: TABLE hasura_user_ranking_trigger; Type: COMMENT; Schema: public; Owner: cindy
--

COMMENT ON TABLE public.hasura_user_ranking_trigger IS 'Trigger table to rank users';


--
-- Name: dialogue_count_ranking(timestamp without time zone, timestamp without time zone); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.dialogue_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) RETURNS SETOF public.hasura_user_ranking_trigger
    LANGUAGE sql STABLE
    AS $$
select
  user_id,
  count(id) as value
from
  dialogue
where
  created >= created_gte
  and created < created_lt
group by user_id $$;


ALTER FUNCTION public.dialogue_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) OWNER TO cindy;


--
-- Name: hasura_direct_message_group_trigger; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.hasura_direct_message_group_trigger (
    user_id integer NOT NULL,
    last_dm_id integer NOT NULL
);


ALTER TABLE public.hasura_direct_message_group_trigger OWNER TO cindy;

--
-- Name: TABLE hasura_direct_message_group_trigger; Type: COMMENT; Schema: public; Owner: cindy
--

COMMENT ON TABLE public.hasura_direct_message_group_trigger IS 'Trigger table for direct message group';


--
-- Name: direct_message_group(integer); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.direct_message_group(user_id integer) RETURNS SETOF public.hasura_direct_message_group_trigger
    LANGUAGE sql STABLE
    AS $$
select
  CASE WHEN sender_id = user_id THEN receiver_id ELSE sender_id END as dm_user_id,
  max(id) as last_dm_id
from
  direct_message
where
  sender_id = user_id or receiver_id = user_id
group by
  dm_user_id
$$;


ALTER FUNCTION public.direct_message_group(user_id integer) OWNER TO cindy;

--
-- Name: maybe_delete_tag_after_puzzle_tag_delete(); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.maybe_delete_tag_after_puzzle_tag_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  puzzle_tag_count INTEGER;
BEGIN
  SELECT count(id) FROM puzzle_tag WHERE tag_id = OLD.tag_id INTO puzzle_tag_count;
  IF puzzle_tag_count = 0 THEN
    DELETE from tag WHERE id = OLD.tag_id;
  END IF;
  RETURN OLD;
END;
$$;


ALTER FUNCTION public.maybe_delete_tag_after_puzzle_tag_delete() OWNER TO cindy;

--
-- Name: puzzle_count_ranking(timestamp without time zone, timestamp without time zone); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.puzzle_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) RETURNS SETOF public.hasura_user_ranking_trigger
    LANGUAGE sql STABLE
    AS $$
select
  user_id,
  count(id) as value
from
  puzzle
where
  created >= created_gte
  and created < created_lt
group by user_id $$;


ALTER FUNCTION public.puzzle_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) OWNER TO cindy;

--
-- Name: star_count_ranking(timestamp without time zone, timestamp without time zone); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.star_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) RETURNS SETOF public.hasura_user_ranking_trigger
    LANGUAGE sql STABLE
    AS $$
select
  puzzle.user_id as user_id,
  count(star) as value
from
  puzzle
left join star on puzzle.id = star.puzzle_id
where
  puzzle.created >= created_gte
  and puzzle.created < created_lt
group by puzzle.user_id $$;


ALTER FUNCTION public.star_count_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) OWNER TO cindy;

--
-- Name: star_sum_ranking(timestamp without time zone, timestamp without time zone); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.star_sum_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) RETURNS SETOF public.hasura_user_ranking_trigger
    LANGUAGE sql STABLE
    AS $$
select
  puzzle.user_id as user_id,
  cast(sum(star.value) as bigint) as value
from
  puzzle
  left join star on puzzle.id = star.puzzle_id
where
  puzzle.created >= created_gte
  and puzzle.created < created_lt
group by puzzle.user_id $$;


ALTER FUNCTION public.star_sum_ranking(created_gte timestamp without time zone, created_lt timestamp without time zone) OWNER TO cindy;

--
-- Name: update_chatmessage_modified(); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.update_chatmessage_modified() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  if OLD.content <> NEW.content then
    NEW.modified = now();
  end if;
  return NEW;
end;
$$;


ALTER FUNCTION public.update_chatmessage_modified() OWNER TO cindy;

--
-- Name: update_dialogue_answer(); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.update_dialogue_answer() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  if OLD.answer <> NEW.answer then
    if OLD.answer = '' then
      NEW.answeredtime = now();
    end if;
  end if;
  NEW.modified = now();
  return NEW;
end;
$$;


ALTER FUNCTION public.update_dialogue_answer() OWNER TO cindy;

--
-- Name: update_hint_modified(); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.update_hint_modified() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  if OLD.content <> NEW.content then
    NEW.modified = now();
  end if;
  return NEW;
end;
$$;


ALTER FUNCTION public.update_hint_modified() OWNER TO cindy;

--
-- Name: update_puzzle_modified(); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.update_puzzle_modified() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  if OLD.status = 0 and NEW.status <> 0 then
    NEW.modified = now();
  end if;
  return NEW;
end;
$$;


ALTER FUNCTION public.update_puzzle_modified() OWNER TO cindy;

--
-- Name: hasura_int_groupby_trigger; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.hasura_int_groupby_trigger (
    "group" integer NOT NULL,
    value bigint NOT NULL
);


ALTER TABLE public.hasura_int_groupby_trigger OWNER TO cindy;

--
-- Name: user_puzzle_genre_groups(integer); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.user_puzzle_genre_groups("userId" integer) RETURNS SETOF public.hasura_int_groupby_trigger
    LANGUAGE sql STABLE
    AS $$
select
  genre as group,
  count(id) as value
from puzzle
where puzzle.user_id = "userId"
group by genre $$;


ALTER FUNCTION public.user_puzzle_genre_groups("userId" integer) OWNER TO cindy;

--
-- Name: user_star_groups(integer); Type: FUNCTION; Schema: public; Owner: cindy
--

CREATE FUNCTION public.user_star_groups("userId" integer) RETURNS SETOF public.hasura_int_groupby_trigger
    LANGUAGE sql STABLE
    AS $$
select
  cast(star_sum as integer) as group,
  count(puzzle_id) as value
from puzzle
left join (
  select puzzle_id, sum(value) as star_sum
  from star
  group by puzzle_id
) as puzzle_stars
on puzzle.id = puzzle_stars.puzzle_id
where puzzle.user_id = "userId" and star_sum is not null
group by star_sum $$;


ALTER FUNCTION public.user_star_groups("userId" integer) OWNER TO cindy;
--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(80) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO cindy;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_id_seq OWNER TO cindy;

--
-- Name: auth_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.auth_group_id_seq OWNED BY public.auth_group.id;


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO cindy;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_group_permissions_id_seq OWNER TO cindy;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.auth_group_permissions_id_seq OWNED BY public.auth_group_permissions.id;


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO cindy;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.auth_permission_id_seq OWNER TO cindy;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.auth_permission_id_seq OWNED BY public.auth_permission.id;


--
-- Name: award; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.award (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    "groupName" character varying(255) NOT NULL,
    requisition text NOT NULL
);


ALTER TABLE public.award OWNER TO cindy;

--
-- Name: award_application; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.award_application (
    id integer NOT NULL,
    status integer NOT NULL,
    comment text NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    reviewed timestamp with time zone,
    applier_id integer NOT NULL,
    award_id integer NOT NULL,
    reviewer_id integer,
    reason text NOT NULL
);


ALTER TABLE public.award_application OWNER TO cindy;

--
-- Name: bookmark; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.bookmark (
    id integer NOT NULL,
    value smallint NOT NULL,
    puzzle_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.bookmark OWNER TO cindy;

--
-- Name: chatmessage; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.chatmessage (
    id integer NOT NULL,
    content text NOT NULL,
    created timestamp with time zone DEFAULT now(),
    "editTimes" integer DEFAULT 0 NOT NULL,
    chatroom_id integer NOT NULL,
    user_id integer NOT NULL,
    modified timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.chatmessage OWNER TO cindy;

--
-- Name: chatroom; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.chatroom (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    created date DEFAULT now() NOT NULL,
    user_id integer NOT NULL,
    private boolean DEFAULT true NOT NULL
);


ALTER TABLE public.chatroom OWNER TO cindy;

--
-- Name: comment; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.comment (
    id integer NOT NULL,
    content text NOT NULL,
    spoiler boolean DEFAULT false NOT NULL,
    puzzle_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.comment OWNER TO cindy;

--
-- Name: dialogue; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.dialogue (
    id integer NOT NULL,
    question text NOT NULL,
    answer text DEFAULT ''::text NOT NULL,
    good boolean DEFAULT false NOT NULL,
    "true" boolean DEFAULT false NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    answeredtime timestamp with time zone,
    puzzle_id integer NOT NULL,
    user_id integer NOT NULL,
    "answerEditTimes" integer DEFAULT 0 NOT NULL,
    "questionEditTimes" integer DEFAULT 0 NOT NULL,
    qno integer DEFAULT 0 NOT NULL,
    modified timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.dialogue OWNER TO cindy;

--
-- Name: direct_message; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.direct_message (
    id integer NOT NULL,
    content text NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    receiver_id integer NOT NULL,
    sender_id integer NOT NULL,
    "editTimes" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.direct_message OWNER TO cindy;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO cindy;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_admin_log_id_seq OWNER TO cindy;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.django_admin_log_id_seq OWNED BY public.django_admin_log.id;


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO cindy;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_content_type_id_seq OWNER TO cindy;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.django_content_type_id_seq OWNED BY public.django_content_type.id;


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO cindy;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.django_migrations_id_seq OWNER TO cindy;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.django_migrations_id_seq OWNED BY public.django_migrations.id;


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO cindy;

--
-- Name: event; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.event (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    banner_img_url character varying(200) NOT NULL,
    status integer NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    page_link character varying(200) NOT NULL,
    page_src text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.event OWNER TO cindy;

--
-- Name: event_award; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.event_award (
    id integer NOT NULL,
    award_id integer NOT NULL,
    event_id integer NOT NULL
);


ALTER TABLE public.event_award OWNER TO cindy;

--
-- Name: favorite_chatroom; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.favorite_chatroom (
    id integer NOT NULL,
    chatroom_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.favorite_chatroom OWNER TO cindy;

--
-- Name: hint; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.hint (
    id integer NOT NULL,
    content text NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    puzzle_id integer NOT NULL,
    edittimes integer DEFAULT 0 NOT NULL,
    receiver_id integer,
    modified timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.hint OWNER TO cindy;

--
-- Name: puzzle; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.puzzle (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    yami integer NOT NULL,
    genre integer NOT NULL,
    content text NOT NULL,
    solution text NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    modified timestamp with time zone DEFAULT now() NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    memo text DEFAULT ''::text NOT NULL,
    user_id integer NOT NULL,
    anonymous boolean DEFAULT false NOT NULL,
    dazed_on date NOT NULL,
    grotesque boolean DEFAULT false NOT NULL
);


ALTER TABLE public.puzzle OWNER TO cindy;

--
-- Name: puzzle_tag; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.puzzle_tag (
    id integer NOT NULL,
    puzzle_id integer NOT NULL,
    tag_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.puzzle_tag OWNER TO cindy;

--
-- Name: replay; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.replay (
    id integer NOT NULL,
    title character varying(255) NOT NULL,
    milestones jsonb NOT NULL,
    puzzle_id integer,
    user_id integer NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.replay OWNER TO cindy;

--
-- Name: replay_dialogue; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.replay_dialogue (
    id integer NOT NULL,
    replay_id integer NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    good boolean NOT NULL,
    "true" boolean NOT NULL,
    keywords jsonb NOT NULL,
    milestones jsonb NOT NULL,
    dependency text NOT NULL
);


ALTER TABLE public.replay_dialogue OWNER TO cindy;

--
-- Name: schedule; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.schedule (
    id integer NOT NULL,
    content text NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    scheduled timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.schedule OWNER TO cindy;

--
-- Name: star; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.star (
    id integer NOT NULL,
    value smallint NOT NULL,
    puzzle_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.star OWNER TO cindy;

--
-- Name: sui_hei_award_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_award_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_award_id_seq OWNER TO cindy;

--
-- Name: sui_hei_award_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_award_id_seq OWNED BY public.award.id;


--
-- Name: sui_hei_awardapplication_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_awardapplication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_awardapplication_id_seq OWNER TO cindy;

--
-- Name: sui_hei_awardapplication_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_awardapplication_id_seq OWNED BY public.award_application.id;


--
-- Name: sui_hei_bookmark_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_bookmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_bookmark_id_seq OWNER TO cindy;

--
-- Name: sui_hei_bookmark_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_bookmark_id_seq OWNED BY public.bookmark.id;


--
-- Name: sui_hei_chatmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_chatmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_chatmessage_id_seq OWNER TO cindy;

--
-- Name: sui_hei_chatmessage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_chatmessage_id_seq OWNED BY public.chatmessage.id;


--
-- Name: sui_hei_chatroom_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_chatroom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_chatroom_id_seq OWNER TO cindy;

--
-- Name: sui_hei_chatroom_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_chatroom_id_seq OWNED BY public.chatroom.id;


--
-- Name: sui_hei_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_comment_id_seq OWNER TO cindy;

--
-- Name: sui_hei_comment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_comment_id_seq OWNED BY public.comment.id;


--
-- Name: sui_hei_dialogue_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_dialogue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_dialogue_id_seq OWNER TO cindy;

--
-- Name: sui_hei_dialogue_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_dialogue_id_seq OWNED BY public.dialogue.id;


--
-- Name: sui_hei_directmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_directmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_directmessage_id_seq OWNER TO cindy;

--
-- Name: sui_hei_directmessage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_directmessage_id_seq OWNED BY public.direct_message.id;


--
-- Name: sui_hei_event_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_event_id_seq OWNER TO cindy;

--
-- Name: sui_hei_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_event_id_seq OWNED BY public.event.id;


--
-- Name: sui_hei_eventaward_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_eventaward_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_eventaward_id_seq OWNER TO cindy;

--
-- Name: sui_hei_eventaward_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_eventaward_id_seq OWNED BY public.event_award.id;


--
-- Name: sui_hei_favoritechatroom_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_favoritechatroom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_favoritechatroom_id_seq OWNER TO cindy;

--
-- Name: sui_hei_favoritechatroom_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_favoritechatroom_id_seq OWNED BY public.favorite_chatroom.id;


--
-- Name: sui_hei_hint_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_hint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_hint_id_seq OWNER TO cindy;

--
-- Name: sui_hei_hint_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_hint_id_seq OWNED BY public.hint.id;


--
-- Name: sui_hei_puzzle_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_puzzle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_puzzle_id_seq OWNER TO cindy;

--
-- Name: sui_hei_puzzle_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_puzzle_id_seq OWNED BY public.puzzle.id;


--
-- Name: sui_hei_puzzle_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_puzzle_tag_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_puzzle_tag_id_seq OWNER TO cindy;

--
-- Name: sui_hei_puzzle_tag_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_puzzle_tag_id_seq OWNED BY public.puzzle_tag.id;


--
-- Name: sui_hei_puzzle_tokenize_cache; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.sui_hei_puzzle_tokenize_cache (
    id integer NOT NULL,
    puzzle_id integer NOT NULL,
    tokens jsonb NOT NULL
);


ALTER TABLE public.sui_hei_puzzle_tokenize_cache OWNER TO cindy;

--
-- Name: sui_hei_puzzle_tokenize_cache_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_puzzle_tokenize_cache_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_puzzle_tokenize_cache_id_seq OWNER TO cindy;

--
-- Name: sui_hei_puzzle_tokenize_cache_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_puzzle_tokenize_cache_id_seq OWNED BY public.sui_hei_puzzle_tokenize_cache.id;


--
-- Name: sui_hei_replay_dialogue_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_replay_dialogue_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_replay_dialogue_id_seq OWNER TO cindy;

--
-- Name: sui_hei_replay_dialogue_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_replay_dialogue_id_seq OWNED BY public.replay_dialogue.id;


--
-- Name: sui_hei_replay_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_replay_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_replay_id_seq OWNER TO cindy;

--
-- Name: sui_hei_replay_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_replay_id_seq OWNED BY public.replay.id;


--
-- Name: sui_hei_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_schedule_id_seq OWNER TO cindy;

--
-- Name: sui_hei_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_schedule_id_seq OWNED BY public.schedule.id;


--
-- Name: sui_hei_star_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_star_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_star_id_seq OWNER TO cindy;

--
-- Name: sui_hei_star_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_star_id_seq OWNED BY public.star.id;


--
-- Name: tag; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.tag (
    id integer NOT NULL,
    name character varying(63) NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.tag OWNER TO cindy;

--
-- Name: sui_hei_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_tag_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_tag_id_seq OWNER TO cindy;

--
-- Name: sui_hei_tag_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_tag_id_seq OWNED BY public.tag.id;


--
-- Name: sui_hei_user_groups; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.sui_hei_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.sui_hei_user_groups OWNER TO cindy;

--
-- Name: sui_hei_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_user_groups_id_seq OWNER TO cindy;

--
-- Name: sui_hei_user_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_user_groups_id_seq OWNED BY public.sui_hei_user_groups.id;


--
-- Name: user; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone DEFAULT now(),
    is_superuser boolean DEFAULT false NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(30) DEFAULT ''::character varying NOT NULL,
    last_name character varying(150) DEFAULT ''::character varying NOT NULL,
    email character varying(254) DEFAULT ''::character varying NOT NULL,
    is_staff boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    date_joined timestamp with time zone DEFAULT now() NOT NULL,
    nickname character varying(255) NOT NULL,
    profile text DEFAULT ''::text NOT NULL,
    current_award_id integer,
    hide_bookmark boolean DEFAULT false NOT NULL,
    last_read_dm_id integer,
    icon character varying(1023) DEFAULT NULL::character varying
);


ALTER TABLE public."user" OWNER TO cindy;

--
-- Name: sui_hei_user_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_user_id_seq OWNER TO cindy;

--
-- Name: sui_hei_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_user_id_seq OWNED BY public."user".id;


--
-- Name: sui_hei_user_user_permissions; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.sui_hei_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.sui_hei_user_user_permissions OWNER TO cindy;

--
-- Name: sui_hei_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_user_user_permissions_id_seq OWNER TO cindy;

--
-- Name: sui_hei_user_user_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_user_user_permissions_id_seq OWNED BY public.sui_hei_user_user_permissions.id;


--
-- Name: user_award; Type: TABLE; Schema: public; Owner: cindy
--

CREATE TABLE public.user_award (
    id integer NOT NULL,
    created date DEFAULT now() NOT NULL,
    award_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.user_award OWNER TO cindy;

--
-- Name: sui_hei_useraward_id_seq; Type: SEQUENCE; Schema: public; Owner: cindy
--

CREATE SEQUENCE public.sui_hei_useraward_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sui_hei_useraward_id_seq OWNER TO cindy;

--
-- Name: sui_hei_useraward_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: cindy
--

ALTER SEQUENCE public.sui_hei_useraward_id_seq OWNED BY public.user_award.id;


--
-- Name: auth_group id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group ALTER COLUMN id SET DEFAULT nextval('public.auth_group_id_seq'::regclass);


--
-- Name: auth_group_permissions id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group_permissions ALTER COLUMN id SET DEFAULT nextval('public.auth_group_permissions_id_seq'::regclass);


--
-- Name: auth_permission id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_permission ALTER COLUMN id SET DEFAULT nextval('public.auth_permission_id_seq'::regclass);


--
-- Name: award id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.award ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_award_id_seq'::regclass);


--
-- Name: award_application id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.award_application ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_awardapplication_id_seq'::regclass);


--
-- Name: bookmark id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.bookmark ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_bookmark_id_seq'::regclass);


--
-- Name: chatmessage id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatmessage ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_chatmessage_id_seq'::regclass);


--
-- Name: chatroom id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatroom ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_chatroom_id_seq'::regclass);


--
-- Name: comment id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.comment ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_comment_id_seq'::regclass);


--
-- Name: dialogue id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.dialogue ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_dialogue_id_seq'::regclass);


--
-- Name: direct_message id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.direct_message ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_directmessage_id_seq'::regclass);


--
-- Name: django_admin_log id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_admin_log ALTER COLUMN id SET DEFAULT nextval('public.django_admin_log_id_seq'::regclass);


--
-- Name: django_content_type id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_content_type ALTER COLUMN id SET DEFAULT nextval('public.django_content_type_id_seq'::regclass);


--
-- Name: django_migrations id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_migrations ALTER COLUMN id SET DEFAULT nextval('public.django_migrations_id_seq'::regclass);


--
-- Name: event id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.event ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_event_id_seq'::regclass);


--
-- Name: event_award id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.event_award ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_eventaward_id_seq'::regclass);


--
-- Name: favorite_chatroom id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.favorite_chatroom ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_favoritechatroom_id_seq'::regclass);


--
-- Name: hint id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hint ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_hint_id_seq'::regclass);


--
-- Name: puzzle id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_puzzle_id_seq'::regclass);


--
-- Name: puzzle_tag id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle_tag ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_puzzle_tag_id_seq'::regclass);


--
-- Name: replay id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.replay ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_replay_id_seq'::regclass);


--
-- Name: replay_dialogue id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.replay_dialogue ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_replay_dialogue_id_seq'::regclass);


--
-- Name: schedule id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.schedule ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_schedule_id_seq'::regclass);


--
-- Name: star id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.star ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_star_id_seq'::regclass);


--
-- Name: sui_hei_puzzle_tokenize_cache id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_puzzle_tokenize_cache ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_puzzle_tokenize_cache_id_seq'::regclass);


--
-- Name: sui_hei_user_groups id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_groups ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_user_groups_id_seq'::regclass);


--
-- Name: sui_hei_user_user_permissions id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_user_permissions ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_user_user_permissions_id_seq'::regclass);


--
-- Name: tag id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.tag ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_tag_id_seq'::regclass);


--
-- Name: user id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public."user" ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_user_id_seq'::regclass);


--
-- Name: user_award id; Type: DEFAULT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.user_award ALTER COLUMN id SET DEFAULT nextval('public.sui_hei_useraward_id_seq'::regclass);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: hasura_direct_message_group_trigger hasura_directmessage_group_trigger_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hasura_direct_message_group_trigger
    ADD CONSTRAINT hasura_directmessage_group_trigger_pkey PRIMARY KEY (user_id);


--
-- Name: hasura_int_groupby_trigger hasura_int_groupby_trigger_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hasura_int_groupby_trigger
    ADD CONSTRAINT hasura_int_groupby_trigger_pkey PRIMARY KEY ("group");


--
-- Name: hasura_user_ranking_trigger hasura_user_ranking_trigger_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hasura_user_ranking_trigger
    ADD CONSTRAINT hasura_user_ranking_trigger_pkey PRIMARY KEY (user_id);


--
-- Name: award sui_hei_award_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.award
    ADD CONSTRAINT sui_hei_award_pkey PRIMARY KEY (id);


--
-- Name: award_application sui_hei_awardapplication_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.award_application
    ADD CONSTRAINT sui_hei_awardapplication_pkey PRIMARY KEY (id);


--
-- Name: bookmark sui_hei_bookmark_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT sui_hei_bookmark_pkey PRIMARY KEY (id);


--
-- Name: bookmark sui_hei_bookmark_puzzle_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT sui_hei_bookmark_puzzle_id_user_id_key UNIQUE (puzzle_id, user_id);


--
-- Name: chatmessage sui_hei_chatmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatmessage
    ADD CONSTRAINT sui_hei_chatmessage_pkey PRIMARY KEY (id);


--
-- Name: chatroom sui_hei_chatroom_name_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatroom
    ADD CONSTRAINT sui_hei_chatroom_name_key UNIQUE (name);


--
-- Name: chatroom sui_hei_chatroom_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatroom
    ADD CONSTRAINT sui_hei_chatroom_pkey PRIMARY KEY (id);


--
-- Name: comment sui_hei_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT sui_hei_comment_pkey PRIMARY KEY (id);


--
-- Name: comment sui_hei_comment_puzzle_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT sui_hei_comment_puzzle_id_user_id_key UNIQUE (puzzle_id, user_id);


--
-- Name: dialogue sui_hei_dialogue_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.dialogue
    ADD CONSTRAINT sui_hei_dialogue_pkey PRIMARY KEY (id);


--
-- Name: direct_message sui_hei_directmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.direct_message
    ADD CONSTRAINT sui_hei_directmessage_pkey PRIMARY KEY (id);


--
-- Name: event sui_hei_event_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT sui_hei_event_pkey PRIMARY KEY (id);


--
-- Name: event_award sui_hei_eventaward_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.event_award
    ADD CONSTRAINT sui_hei_eventaward_pkey PRIMARY KEY (id);


--
-- Name: favorite_chatroom sui_hei_favoritechatroom_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.favorite_chatroom
    ADD CONSTRAINT sui_hei_favoritechatroom_pkey PRIMARY KEY (id);


--
-- Name: hint sui_hei_hint_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hint
    ADD CONSTRAINT sui_hei_hint_pkey PRIMARY KEY (id);


--
-- Name: puzzle sui_hei_puzzle_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle
    ADD CONSTRAINT sui_hei_puzzle_pkey PRIMARY KEY (id);


--
-- Name: puzzle_tag sui_hei_puzzle_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle_tag
    ADD CONSTRAINT sui_hei_puzzle_tag_pkey PRIMARY KEY (id);


--
-- Name: puzzle_tag sui_hei_puzzle_tag_puzzle_id_tag_id_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle_tag
    ADD CONSTRAINT sui_hei_puzzle_tag_puzzle_id_tag_id_key UNIQUE (puzzle_id, tag_id);


--
-- Name: sui_hei_puzzle_tokenize_cache sui_hei_puzzle_tokenize_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_puzzle_tokenize_cache
    ADD CONSTRAINT sui_hei_puzzle_tokenize_cache_pkey PRIMARY KEY (id);


--
-- Name: sui_hei_puzzle_tokenize_cache sui_hei_puzzle_tokenize_cache_puzzle_id_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_puzzle_tokenize_cache
    ADD CONSTRAINT sui_hei_puzzle_tokenize_cache_puzzle_id_key UNIQUE (puzzle_id);


--
-- Name: replay_dialogue sui_hei_replay_dialogue_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.replay_dialogue
    ADD CONSTRAINT sui_hei_replay_dialogue_pkey PRIMARY KEY (id);


--
-- Name: replay sui_hei_replay_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.replay
    ADD CONSTRAINT sui_hei_replay_pkey PRIMARY KEY (id);


--
-- Name: schedule sui_hei_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT sui_hei_schedule_pkey PRIMARY KEY (id);


--
-- Name: star sui_hei_star_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.star
    ADD CONSTRAINT sui_hei_star_pkey PRIMARY KEY (id);


--
-- Name: star sui_hei_star_puzzle_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.star
    ADD CONSTRAINT sui_hei_star_puzzle_id_user_id_key UNIQUE (puzzle_id, user_id);


--
-- Name: tag sui_hei_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT sui_hei_tag_name_key UNIQUE (name);


--
-- Name: tag sui_hei_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.tag
    ADD CONSTRAINT sui_hei_tag_pkey PRIMARY KEY (id);


--
-- Name: sui_hei_user_groups sui_hei_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_groups
    ADD CONSTRAINT sui_hei_user_groups_pkey PRIMARY KEY (id);


--
-- Name: sui_hei_user_groups sui_hei_user_groups_user_id_group_id_3e3ddec8_uniq; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_groups
    ADD CONSTRAINT sui_hei_user_groups_user_id_group_id_3e3ddec8_uniq UNIQUE (user_id, group_id);


--
-- Name: user sui_hei_user_nickname_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT sui_hei_user_nickname_key UNIQUE (nickname);


--
-- Name: user sui_hei_user_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT sui_hei_user_pkey PRIMARY KEY (id);


--
-- Name: sui_hei_user_user_permissions sui_hei_user_user_permis_user_id_permission_id_062a5bb1_uniq; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_user_permissions
    ADD CONSTRAINT sui_hei_user_user_permis_user_id_permission_id_062a5bb1_uniq UNIQUE (user_id, permission_id);


--
-- Name: sui_hei_user_user_permissions sui_hei_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_user_permissions
    ADD CONSTRAINT sui_hei_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: user sui_hei_user_username_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT sui_hei_user_username_key UNIQUE (username);


--
-- Name: user_award sui_hei_useraward_award_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.user_award
    ADD CONSTRAINT sui_hei_useraward_award_id_user_id_key UNIQUE (award_id, user_id);


--
-- Name: user_award sui_hei_useraward_pkey; Type: CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.user_award
    ADD CONSTRAINT sui_hei_useraward_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: sui_hei_awardapplication_applier_id_00be222b; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_awardapplication_applier_id_00be222b ON public.award_application USING btree (applier_id);


--
-- Name: sui_hei_awardapplication_award_id_aa0cc08a; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_awardapplication_award_id_aa0cc08a ON public.award_application USING btree (award_id);


--
-- Name: sui_hei_awardapplication_reviewer_id_4c609c4f; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_awardapplication_reviewer_id_4c609c4f ON public.award_application USING btree (reviewer_id);


--
-- Name: sui_hei_bookmark_puzzle_id_0211175c; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_bookmark_puzzle_id_0211175c ON public.bookmark USING btree (puzzle_id);


--
-- Name: sui_hei_bookmark_user_id_475bb3c8; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_bookmark_user_id_475bb3c8 ON public.bookmark USING btree (user_id);


--
-- Name: sui_hei_chatmessage_chatroom_id_d15d65e3; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_chatmessage_chatroom_id_d15d65e3 ON public.chatmessage USING btree (chatroom_id);


--
-- Name: sui_hei_chatmessage_user_id_87bd67f6; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_chatmessage_user_id_87bd67f6 ON public.chatmessage USING btree (user_id);


--
-- Name: sui_hei_chatroom_name_b0f36b4b_like; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_chatroom_name_b0f36b4b_like ON public.chatroom USING btree (name varchar_pattern_ops);


--
-- Name: sui_hei_chatroom_user_id_23e4cf24; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_chatroom_user_id_23e4cf24 ON public.chatroom USING btree (user_id);


--
-- Name: sui_hei_comment_puzzle_id_32dbe3f7; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_comment_puzzle_id_32dbe3f7 ON public.comment USING btree (puzzle_id);


--
-- Name: sui_hei_comment_user_id_e0e82347; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_comment_user_id_e0e82347 ON public.comment USING btree (user_id);


--
-- Name: sui_hei_dialogue_puzzle_id_d736d013; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_dialogue_puzzle_id_d736d013 ON public.dialogue USING btree (puzzle_id);


--
-- Name: sui_hei_dialogue_user_id_7dba009f; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_dialogue_user_id_7dba009f ON public.dialogue USING btree (user_id);


--
-- Name: sui_hei_directmessage_receiver_id_6fe1b1da; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_directmessage_receiver_id_6fe1b1da ON public.direct_message USING btree (receiver_id);


--
-- Name: sui_hei_directmessage_sender_id_47575dca; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_directmessage_sender_id_47575dca ON public.direct_message USING btree (sender_id);


--
-- Name: sui_hei_event_user_id_574c9deb; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_event_user_id_574c9deb ON public.event USING btree (user_id);


--
-- Name: sui_hei_eventaward_award_id_1593f1e9; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_eventaward_award_id_1593f1e9 ON public.event_award USING btree (award_id);


--
-- Name: sui_hei_eventaward_event_id_ee7fc23d; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_eventaward_event_id_ee7fc23d ON public.event_award USING btree (event_id);


--
-- Name: sui_hei_favoritechatroom_chatroom_id_a416c6fc; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_favoritechatroom_chatroom_id_a416c6fc ON public.favorite_chatroom USING btree (chatroom_id);


--
-- Name: sui_hei_favoritechatroom_user_id_123a5e18; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_favoritechatroom_user_id_123a5e18 ON public.favorite_chatroom USING btree (user_id);


--
-- Name: sui_hei_hint_puzzle_id_b4edfab8; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_hint_puzzle_id_b4edfab8 ON public.hint USING btree (puzzle_id);


--
-- Name: sui_hei_puzzle_user_id_946a9f35; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_puzzle_user_id_946a9f35 ON public.puzzle USING btree (user_id);


--
-- Name: sui_hei_schedule_user_id_6fb7eb62; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_schedule_user_id_6fb7eb62 ON public.schedule USING btree (user_id);


--
-- Name: sui_hei_star_puzzle_id_8db2a6e5; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_star_puzzle_id_8db2a6e5 ON public.star USING btree (puzzle_id);


--
-- Name: sui_hei_star_user_id_68775e93; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_star_user_id_68775e93 ON public.star USING btree (user_id);


--
-- Name: sui_hei_user_current_award_id_3d1f767d; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_current_award_id_3d1f767d ON public."user" USING btree (current_award_id);


--
-- Name: sui_hei_user_groups_group_id_c3cf2d84; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_groups_group_id_c3cf2d84 ON public.sui_hei_user_groups USING btree (group_id);


--
-- Name: sui_hei_user_groups_user_id_995095f6; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_groups_user_id_995095f6 ON public.sui_hei_user_groups USING btree (user_id);


--
-- Name: sui_hei_user_last_read_dm_id_b9786238; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_last_read_dm_id_b9786238 ON public."user" USING btree (last_read_dm_id);


--
-- Name: sui_hei_user_nickname_269f1fc5_like; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_nickname_269f1fc5_like ON public."user" USING btree (nickname varchar_pattern_ops);


--
-- Name: sui_hei_user_user_permissions_permission_id_19bc3f00; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_user_permissions_permission_id_19bc3f00 ON public.sui_hei_user_user_permissions USING btree (permission_id);


--
-- Name: sui_hei_user_user_permissions_user_id_2c881b71; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_user_permissions_user_id_2c881b71 ON public.sui_hei_user_user_permissions USING btree (user_id);


--
-- Name: sui_hei_user_username_873d30f0_like; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_user_username_873d30f0_like ON public."user" USING btree (username varchar_pattern_ops);


--
-- Name: sui_hei_useraward_award_id_8d4a868f; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_useraward_award_id_8d4a868f ON public.user_award USING btree (award_id);


--
-- Name: sui_hei_useraward_user_id_1145009e; Type: INDEX; Schema: public; Owner: cindy
--

CREATE INDEX sui_hei_useraward_user_id_1145009e ON public.user_award USING btree (user_id);


--
-- Name: dialogue add_dialogue_qno_before_dialogue_insert_trigger; Type: TRIGGER; Schema: public; Owner: cindy
--

CREATE TRIGGER add_dialogue_qno_before_dialogue_insert_trigger BEFORE INSERT ON public.dialogue FOR EACH ROW EXECUTE FUNCTION public.add_dialogue_qno_before_dialogue_insert();


--
-- Name: puzzle add_puzzle_chatroom_after_puzzle_insert_trigger; Type: TRIGGER; Schema: public; Owner: cindy
--

CREATE TRIGGER add_puzzle_chatroom_after_puzzle_insert_trigger AFTER INSERT ON public.puzzle FOR EACH ROW EXECUTE FUNCTION public.add_puzzle_chatroom_after_puzzle_insert();


--
-- Name: puzzle_tag maybe_delete_tag_after_puzzle_tag_delete_trigger; Type: TRIGGER; Schema: public; Owner: cindy
--

CREATE TRIGGER maybe_delete_tag_after_puzzle_tag_delete_trigger AFTER DELETE ON public.puzzle_tag FOR EACH ROW EXECUTE FUNCTION public.maybe_delete_tag_after_puzzle_tag_delete();


--
-- Name: dialogue update_answer_dialogue_answer_trigger; Type: TRIGGER; Schema: public; Owner: cindy
--

CREATE TRIGGER update_answer_dialogue_answer_trigger BEFORE UPDATE ON public.dialogue FOR EACH ROW EXECUTE FUNCTION public.update_dialogue_answer();


--
-- Name: chatmessage update_chatmessage_modified_trigger; Type: TRIGGER; Schema: public; Owner: cindy
--

CREATE TRIGGER update_chatmessage_modified_trigger BEFORE UPDATE ON public.chatmessage FOR EACH ROW EXECUTE FUNCTION public.update_chatmessage_modified();


--
-- Name: hint update_hint_modified_trigger; Type: TRIGGER; Schema: public; Owner: cindy
--

CREATE TRIGGER update_hint_modified_trigger BEFORE UPDATE ON public.hint FOR EACH ROW EXECUTE FUNCTION public.update_hint_modified();


--
-- Name: puzzle update_puzzle_modified_trigger; Type: TRIGGER; Schema: public; Owner: cindy
--

CREATE TRIGGER update_puzzle_modified_trigger BEFORE UPDATE ON public.puzzle FOR EACH ROW EXECUTE FUNCTION public.update_puzzle_modified();


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: hasura_direct_message_group_trigger hasura_directmessage_group_trigger_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hasura_direct_message_group_trigger
    ADD CONSTRAINT hasura_directmessage_group_trigger_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: hasura_user_ranking_trigger hasura_user_ranking_trigger_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hasura_user_ranking_trigger
    ADD CONSTRAINT hasura_user_ranking_trigger_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: award_application sui_hei_awardapplica_reviewer_id_4c609c4f_fk_sui_hei_u; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.award_application
    ADD CONSTRAINT sui_hei_awardapplica_reviewer_id_4c609c4f_fk_sui_hei_u FOREIGN KEY (reviewer_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: award_application sui_hei_awardapplication_applier_id_00be222b_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.award_application
    ADD CONSTRAINT sui_hei_awardapplication_applier_id_00be222b_fk_sui_hei_user_id FOREIGN KEY (applier_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: award_application sui_hei_awardapplication_award_id_aa0cc08a_fk_sui_hei_award_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.award_application
    ADD CONSTRAINT sui_hei_awardapplication_award_id_aa0cc08a_fk_sui_hei_award_id FOREIGN KEY (award_id) REFERENCES public.award(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmark sui_hei_bookmark_puzzle_id_0211175c_fk_sui_hei_puzzle_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT sui_hei_bookmark_puzzle_id_0211175c_fk_sui_hei_puzzle_id FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookmark sui_hei_bookmark_user_id_475bb3c8_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.bookmark
    ADD CONSTRAINT sui_hei_bookmark_user_id_475bb3c8_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chatmessage sui_hei_chatmessage_chatroom_id_d15d65e3_fk_sui_hei_chatroom_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatmessage
    ADD CONSTRAINT sui_hei_chatmessage_chatroom_id_d15d65e3_fk_sui_hei_chatroom_id FOREIGN KEY (chatroom_id) REFERENCES public.chatroom(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chatmessage sui_hei_chatmessage_user_id_87bd67f6_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatmessage
    ADD CONSTRAINT sui_hei_chatmessage_user_id_87bd67f6_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chatroom sui_hei_chatroom_user_id_23e4cf24_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.chatroom
    ADD CONSTRAINT sui_hei_chatroom_user_id_23e4cf24_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comment sui_hei_comment_puzzle_id_32dbe3f7_fk_sui_hei_puzzle_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT sui_hei_comment_puzzle_id_32dbe3f7_fk_sui_hei_puzzle_id FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comment sui_hei_comment_user_id_e0e82347_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT sui_hei_comment_user_id_e0e82347_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dialogue sui_hei_dialogue_puzzle_id_d736d013_fk_sui_hei_puzzle_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.dialogue
    ADD CONSTRAINT sui_hei_dialogue_puzzle_id_d736d013_fk_sui_hei_puzzle_id FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dialogue sui_hei_dialogue_user_id_7dba009f_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.dialogue
    ADD CONSTRAINT sui_hei_dialogue_user_id_7dba009f_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: direct_message sui_hei_directmessage_receiver_id_6fe1b1da_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.direct_message
    ADD CONSTRAINT sui_hei_directmessage_receiver_id_6fe1b1da_fk_sui_hei_user_id FOREIGN KEY (receiver_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: direct_message sui_hei_directmessage_sender_id_47575dca_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.direct_message
    ADD CONSTRAINT sui_hei_directmessage_sender_id_47575dca_fk_sui_hei_user_id FOREIGN KEY (sender_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: event sui_hei_event_user_id_574c9deb_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT sui_hei_event_user_id_574c9deb_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: event_award sui_hei_eventaward_award_id_1593f1e9_fk_sui_hei_award_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.event_award
    ADD CONSTRAINT sui_hei_eventaward_award_id_1593f1e9_fk_sui_hei_award_id FOREIGN KEY (award_id) REFERENCES public.award(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: event_award sui_hei_eventaward_event_id_ee7fc23d_fk_sui_hei_event_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.event_award
    ADD CONSTRAINT sui_hei_eventaward_event_id_ee7fc23d_fk_sui_hei_event_id FOREIGN KEY (event_id) REFERENCES public.event(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: favorite_chatroom sui_hei_favoritechat_chatroom_id_a416c6fc_fk_sui_hei_c; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.favorite_chatroom
    ADD CONSTRAINT sui_hei_favoritechat_chatroom_id_a416c6fc_fk_sui_hei_c FOREIGN KEY (chatroom_id) REFERENCES public.chatroom(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: favorite_chatroom sui_hei_favoritechatroom_user_id_123a5e18_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.favorite_chatroom
    ADD CONSTRAINT sui_hei_favoritechatroom_user_id_123a5e18_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: hint sui_hei_hint_puzzle_id_b4edfab8_fk_sui_hei_puzzle_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hint
    ADD CONSTRAINT sui_hei_hint_puzzle_id_b4edfab8_fk_sui_hei_puzzle_id FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: hint sui_hei_hint_receiver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.hint
    ADD CONSTRAINT sui_hei_hint_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public."user"(id);


--
-- Name: puzzle_tag sui_hei_puzzle_tag_puzzle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle_tag
    ADD CONSTRAINT sui_hei_puzzle_tag_puzzle_id_fkey FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: puzzle_tag sui_hei_puzzle_tag_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle_tag
    ADD CONSTRAINT sui_hei_puzzle_tag_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tag(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: puzzle_tag sui_hei_puzzle_tag_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle_tag
    ADD CONSTRAINT sui_hei_puzzle_tag_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: sui_hei_puzzle_tokenize_cache sui_hei_puzzle_tokenize_cache_puzzle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_puzzle_tokenize_cache
    ADD CONSTRAINT sui_hei_puzzle_tokenize_cache_puzzle_id_fkey FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: puzzle sui_hei_puzzle_user_id_946a9f35_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.puzzle
    ADD CONSTRAINT sui_hei_puzzle_user_id_946a9f35_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: replay_dialogue sui_hei_replay_dialogue_replay_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.replay_dialogue
    ADD CONSTRAINT sui_hei_replay_dialogue_replay_id_fkey FOREIGN KEY (replay_id) REFERENCES public.replay(id) ON UPDATE RESTRICT ON DELETE CASCADE;


--
-- Name: replay sui_hei_replay_puzzle_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.replay
    ADD CONSTRAINT sui_hei_replay_puzzle_id_fkey FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: replay sui_hei_replay_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.replay
    ADD CONSTRAINT sui_hei_replay_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- Name: schedule sui_hei_schedule_user_id_6fb7eb62_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT sui_hei_schedule_user_id_6fb7eb62_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: star sui_hei_star_puzzle_id_8db2a6e5_fk_sui_hei_puzzle_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.star
    ADD CONSTRAINT sui_hei_star_puzzle_id_8db2a6e5_fk_sui_hei_puzzle_id FOREIGN KEY (puzzle_id) REFERENCES public.puzzle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: star sui_hei_star_user_id_68775e93_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.star
    ADD CONSTRAINT sui_hei_star_user_id_68775e93_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user sui_hei_user_current_award_id_3d1f767d_fk_sui_hei_useraward_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT sui_hei_user_current_award_id_3d1f767d_fk_sui_hei_useraward_id FOREIGN KEY (current_award_id) REFERENCES public.user_award(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sui_hei_user_groups sui_hei_user_groups_group_id_c3cf2d84_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_groups
    ADD CONSTRAINT sui_hei_user_groups_group_id_c3cf2d84_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sui_hei_user_groups sui_hei_user_groups_user_id_995095f6_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_groups
    ADD CONSTRAINT sui_hei_user_groups_user_id_995095f6_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user sui_hei_user_last_read_dm_id_b9786238_fk_sui_hei_d; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT sui_hei_user_last_read_dm_id_b9786238_fk_sui_hei_d FOREIGN KEY (last_read_dm_id) REFERENCES public.direct_message(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sui_hei_user_user_permissions sui_hei_user_user_pe_permission_id_19bc3f00_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_user_permissions
    ADD CONSTRAINT sui_hei_user_user_pe_permission_id_19bc3f00_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sui_hei_user_user_permissions sui_hei_user_user_pe_user_id_2c881b71_fk_sui_hei_u; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.sui_hei_user_user_permissions
    ADD CONSTRAINT sui_hei_user_user_pe_user_id_2c881b71_fk_sui_hei_u FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_award sui_hei_useraward_award_id_8d4a868f_fk_sui_hei_award_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.user_award
    ADD CONSTRAINT sui_hei_useraward_award_id_8d4a868f_fk_sui_hei_award_id FOREIGN KEY (award_id) REFERENCES public.award(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_award sui_hei_useraward_user_id_1145009e_fk_sui_hei_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cindy
--

ALTER TABLE ONLY public.user_award
    ADD CONSTRAINT sui_hei_useraward_user_id_1145009e_fk_sui_hei_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

